### ISSUE TITLE
Add additional TFM

### ISSUE THREAD

**Issue by thompson-tomo** [YohDeadfall/Yoh.Text.Json.NamingPolicies#88]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when also targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by YohDeadfall** [comment]
Totally makes sense.

**Comment by YohDeadfall** [comment]
Okay, I checked it and since it targets .NET Standard 2 it covers all the possible targets including .NET Framework 4.6.1. Therefore, you shall have no issue referencing the package, but perhaps you meant the number of packages pulled from Nuget even if most of them only forwarding types to .NET Framework dlls, right?

**Comment by thompson-tomo** [comment]
Correct I am wanting to reduce the number of dependencies being brought in from nuget.org as it is additional packages needing to be maintained.

**Comment by YohDeadfall** [comment]
@eiriktsarpalis, is the idea of using .NET Framework 4.6.2 as a target for `System.Text.Json`  to reduce number of dependencies? Currently I see a little value in adding another TFM because .NET Standard 2 covers any other target, but the amount of forward only libraries is definitely huge compared to when `System.Text.Json` for .NET Framework is targeted.

**Comment by eiriktsarpalis** [comment]
No, I think it's just because net462 is still supported but it also doesn't implement netstandard2.0 (IIRC net47x is the earliest TFM that implements it)

**Comment by YohDeadfall** [comment]
Actually .NET 4.6.2 implements .NET Standard 2.0 according to [the docs](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0) and what I see for the package. So, `System.Tet.Json` can be used even not being directly targeting `net462`. Even with `net461`.

What would be your advice on the topic? I mean the position according to the guidelines for .NET ecosystem.
